[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
line_length = 88
profile = "django"
sections=[
  "FUTURE",
  "STDLIB",
  "THIRDPARTY",
  "FIRSTPARTY",
  "TESTS",
  "LOCALFOLDER"
]
default_section = "THIRDPARTY"
known_first_party = ["django"]
known_tests = "./*/tests.py"
multi_line_output = 3
include_trailing_comma = true
combine_as_imports = true

[tool.flake8]
max-line-length = 88
# see https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes
# for error codes. The ones we ignore are:
#   W503: line break before binary operator
#   W504: line break after binary operator
#   E203: whitespace before ':' (which is contrary to pep8?)
#   E731: do not assign a lambda expression, use a def
#   E501: Line too long (black enforces this for us)
ignore = [
    "W503",
    "W504",
    "E203",
    "E731",
    "E501"
]
exclude = [
    "env",
    ".venv",
    ".env",
    "./*/tests.py",
]
